export const instagram = "https://www.instagram.com/bethanyugc/";
export const email = "beth.ugcontent@gmail.com";
export const portrait = "/media/264be5e8b4397231.jpg";
export type Work = { id: string; brand: string; title: string; category: string; format: string; video: string; poster: string; description: string };
const media = (name: string) => `/media/${name}`;
export const works: Work[] = [
  { id: "elemis", brand: "ELEMIS", title: "A little everyday self-care", category: "Beauty & wellness", format: "Creative", video: media("c2e9b6d1f0ca32739031c2658f17b4e7.mp4"), poster: media("6eda0ff42ea8e7a147202859a6aa534a.jpg"), description: "A playful, personal take on a skincare routine, bringing the product into an everyday moment." },
  { id: "pots-for-tots", brand: "Pots for Tots", title: "From doorstep to dinnertime", category: "Motherhood", format: "Unboxing", video: media("7dc667246184be88be6cfec5e447515c.mp4"), poster: media("64db133a0b3a7b81b86f461ef0043bd3.jpg"), description: "An unboxing that brings a family food delivery to life, from the first look to the little details." },
  { id: "milk-and-more", brand: "Milk & More", title: "Making mornings a little easier", category: "Lifestyle", format: "Problem / solution", video: media("483ba5641347cd48751a6071c58d7d8c.mp4"), poster: media("978b4461019f5dc86d34c660a9104e89.jpg"), description: "An everyday household problem becomes the starting point for a relatable product story." },
  { id: "baby-show", brand: "The Baby Show", title: "Come along for a family day out", category: "Motherhood", format: "Event coverage", video: media("bc137bef0c4add4182481a2d9c828c2c.mp4"), poster: media("94680948ed5169e2420a5431ff63c814.jpg"), description: "A creator’s-eye view of The Baby Show, capturing the atmosphere and experience in person." },
  { id: "tonic", brand: "Tonic Health", title: "Wellness, in real life", category: "Beauty & wellness", format: "Wellness review", video: media("a17a1a40cceb1b4c0a7adbcfd6f97ac9.mp4"), poster: media("21b2d97e7c3f25a7f0a14a49a6d0c85f.jpg"), description: "A product-led wellness example that makes a daily routine feel approachable." },
  { id: "essence-vault", brand: "The Essence Vault", title: "The fragrance conversation", category: "Beauty & wellness", format: "Talk to camera", video: media("2831f8b12068b2d7a785afa1018a2771.mp4"), poster: media("9e7aeadf85fbb82bc5b1dc519fada307.jpg"), description: "A conversational fragrance review delivered straight to camera, with the feel of a recommendation from a friend." },
  { id: "hipp", brand: "HiPP Organic", title: "A little find on the weekly shop", category: "Motherhood", format: "In-store", video: media("37aa7ab8f260b936ea66700131c1c31b.mp4"), poster: media("92348d57a82d42592719f67827bd4326.jpg"), description: "An in-store product discovery, showing where the brand fits into a real shopping trip." },
  { id: "fortis", brand: "Fortis", title: "Let’s talk about the details", category: "Beauty & wellness", format: "Product review", video: media("a5306a28225de946ef431a999f1e0ff7.mp4"), poster: media("908da37196ef2582fff3be92cffbb571.jpg"), description: "A hands-on product review, putting the experience front and centre." },
  { id: "euthymol", brand: "Euthymol", title: "A fresh take on the daily routine", category: "Lifestyle", format: "Product review", video: media("d14c89bfeffb7978567c59f8476c5c3f.mp4"), poster: media("b3f42fe687f6e085737b4fbed43c9902.jpg"), description: "A product review set in a real home, bringing an everyday routine into the story." },
];
export const brands = ["ELEMIS", "HiPP Organic", "Milk & More", "The Baby Show", "Pots for Tots", "Bibado", "Tonic Health", "Jaques of London", "The Essence Vault", "EasyTots", "BABYGO", "Euthymol", "Fortis", "MailBakes", "Designed By Sports"];
export const reels: Work[] = [
  { id: "DdG-O_8NMLx", brand: "From Instagram", title: "A day with the creator club", category: "Lifestyle", format: "Behind the scenes", video: media("instagram-DdG-O_8NMLx.mp4"), poster: media("instagram-DdG-O_8NMLx.jpg"), description: "A day with Cool Mama Creator Club, from Bethany’s Instagram." },
  { id: "DdEgnu_NrEv", brand: "From Instagram", title: "Nap time. Coffee. Content.", category: "Lifestyle", format: "Creator life", video: media("instagram-DdEgnu_NrEv.mp4"), poster: media("instagram-DdEgnu_NrEv.jpg"), description: "Finding a moment for the business of creating, between the everyday moments of motherhood." },
  { id: "DcOLk09Nghp", brand: "From Instagram", title: "A realistic day with me", category: "Motherhood", format: "Day in the life", video: media("instagram-DcOLk09Nghp.mp4"), poster: media("instagram-DcOLk09Nghp.jpg"), description: "Real life as a mum of two and content creator." },
];
export const services = [
  { number: "01", title: "UGC that feels like real life.", short: "Organic UGC", description: "Natural, relatable videos for your social channels. Product demos, unboxings, daily routines and lifestyle storytelling that give your brand a human voice.", tags: ["Reels & short-form video", "Product demos", "Unboxings"] },
  { number: "02", title: "Creative with a strategy behind it.", short: "Paid ad creative", description: "Bring a marketing perspective to your next campaign. Clear hooks, product benefits and a reason to take the next step, delivered in a voice that feels natural.", tags: ["Problem / solution", "Talk-to-camera", "Hook variations"] },
  { number: "03", title: "Let your product do the talking.", short: "Reviews & testimonials", description: "Thoughtful, hands-on content that explores the product experience. Show your audience how it works and where it fits into their everyday lives.", tags: ["Product reviews", "Demonstrations", "First impressions"] },
  { number: "04", title: "More moments. More connection.", short: "Ongoing partnerships", description: "Build a consistent content library together. Monthly retainers, in-person events and custom packages shaped around what your brand needs next.", tags: ["Monthly retainers", "Event coverage", "Custom packages"] },
];
