import Link from "next/link";
import { ArrowUpRight, Heart, MapPin, Sparkles } from "lucide-react";
import { portrait, services } from "@/lib/content";
import { CTA } from "@/components/site";
import { WorkGallery } from "@/components/work-gallery";
import { InstagramFeed } from "@/components/instagram-feed";

export default function Home() {
  return <>
    <section className="hero container"><div className="hero-copy"><span className="eyebrow hero-eyebrow"><span className="little-dot"/> UK UGC CREATOR & MARKETING MIND</span><h1>Real moments.<br/>Thoughtful content.<br/><em>A little bit of Beth.</em></h1><p>I turn everyday life into content your audience sees themselves in. Motherhood, lifestyle and a little self-care — with a marketing brain behind the camera.</p><div className="button-row"><Link href="/work" className="button">Explore my work <ArrowUpRight size={18}/></Link><Link href="/contact" className="text-link">Let’s create together <ArrowUpRight size={17}/></Link></div><div className="hero-location"><MapPin size={14}/> Essex, UK <span>·</span> Mum of two <span>·</span> Creator with purpose</div></div><div className="hero-visual"><div className="portrait-arch"><img src={portrait} alt="Bethany smiling, the creator behind Bethany UGC" fetchPriority="high"/><div className="portrait-caption"><span>Hi, I’m Beth</span><Heart size={22} strokeWidth={1.3}/></div></div><div className="creator-stamp"><Sparkles size={22}/><span>REAL LIFE.<br/>REAL CONNECTION.</span></div><Link className="hero-mini-reel" href="/work#elemis" aria-label="Explore Bethany’s skincare content"><img src="/media/6eda0ff42ea8e7a147202859a6aa534a.jpg" alt="Bethany’s ELEMIS skincare video"/><span>a little self-care <ArrowUpRight size={14}/></span></Link><span className="hero-handwritten">your brand, in real life</span><svg className="doodle-arrow" viewBox="0 0 100 65" fill="none" aria-hidden="true"><path d="M3 8C35 1 73 9 68 32S29 60 25 43s32-20 65 9m-4-16 5 17-19 1" stroke="currentColor" strokeWidth="1.5"/></svg></div></section>
    <section className="brand-strip"><div className="container"><p className="eyebrow">A FEW BRANDS I’VE CREATED FOR</p><div className="brand-logos"><span className="brand-elemis">ELEMIS</span><span className="brand-hipp">HiPP <small>ORGANIC</small></span><span className="brand-milk">Milk &<br/>More</span><span className="brand-baby">the <b>Baby</b> show</span><span className="brand-pots">Pots for Tots</span><span className="brand-bibado">BIBADO</span></div></div></section>
    <section className="section-pad container" id="selected-work"><div className="section-heading"><div><span className="eyebrow">A LITTLE OF WHAT I DO</span><h2>Made for brands.<br/><em>Meant for real people.</em></h2></div><div className="section-heading-aside"><p>From the school run to the skincare shelf.<br/>Content that fits naturally into everyday life.</p><Link href="/work" className="text-link">View all work <ArrowUpRight size={17}/></Link></div></div><WorkGallery featured/></section>
    <section className="about-preview"><div className="container about-preview-grid"><div className="about-photo"><img src="/media/instagram-DcOLk09Nghp.jpg" alt="A day in the life of Beth, mum of two and content creator" loading="lazy"/><span className="photo-note">the person behind the content ♡</span></div><div className="about-copy"><span className="eyebrow">CREATOR BY HEART. MARKETER BY EXPERIENCE.</span><h2>I think like a brand.<br/><em>I create like a human.</em></h2><p>I’m Beth — a mum of two, UGC creator and marketing expert based in Essex. I know the juggle, the little wins, and the products that become part of a family’s everyday.</p><p>With over 10 years in marketing, I bring more than a camera. I bring an understanding of your audience, your goals, and the story worth telling.</p><div className="about-facts"><div><strong>10+</strong><span>years in marketing</span></div><div><strong>2</strong><span>little sources of inspiration</span></div><div><Heart size={30} strokeWidth={1}/><span>real life at the heart</span></div></div><Link href="/about" className="text-link">A little more about me <ArrowUpRight size={17}/></Link></div></div></section>
    <section className="section-pad container"><div className="section-heading"><div><span className="eyebrow">LET’S MAKE SOMETHING GOOD</span><h2>Your story. <em>My creative touch.</em></h2></div><Link href="/services" className="text-link">Ways to work together <ArrowUpRight size={17}/></Link></div><div className="service-preview-grid">{services.map(s=><Link href="/services" className="service-preview" key={s.number}><span className="service-number">{s.number}</span><h3>{s.short}</h3><p>{s.description.split(". ")[0]}.</p><ArrowUpRight size={22}/></Link>)}</div></section>
    <div className="manifesto"><span>Real stories</span><Sparkles/><span>Thoughtful strategy</span><Sparkles/><span>Content with heart</span><Sparkles/><span>A natural connection</span></div>
    <InstagramFeed/><CTA/>
  </>;
}
