"use client";
import { useState, type FormEvent } from "react";
import { ArrowUpRight, Check, Copy, Mail } from "lucide-react";
import { email } from "@/lib/content";

export function ContactForm() {
  const [brief,setBrief]=useState(""); const [subject,setSubject]=useState(""); const [copied,setCopied]=useState(false);
  function prepare(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data=new FormData(event.currentTarget);
    setSubject(`UGC enquiry — ${data.get("brand")}`);
    setBrief(`Hi Beth,\n\nI’m ${data.get("name")} from ${data.get("brand")}.\n\nEmail: ${data.get("email")}\nInterested in: ${data.get("service")}\nBudget: ${data.get("budget")}\nTimeline: ${data.get("timeline")||"Flexible"}\n\nProject brief:\n${data.get("message")}\n\nLooking forward to chatting!\n${data.get("name")}`);
    setCopied(false);
  }
  return <div className="contact-form-wrap"><form onSubmit={prepare} className="contact-form"><div className="form-row"><label>Your name<input name="name" autoComplete="name" required maxLength={100} placeholder="First and last name"/></label><label>Brand / agency<input name="brand" autoComplete="organization" required maxLength={150} placeholder="Who are you creating for?"/></label></div><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={200} placeholder="you@yourbrand.com"/></label><label>What do you have in mind?<select name="service" defaultValue="" required><option value="" disabled>Select a service</option><option>Organic UGC</option><option>Paid ad creative</option><option>Reviews & testimonials</option><option>Monthly retainer</option><option>Event coverage</option><option>Custom project / let’s explore</option></select></label><div className="form-row"><label>Project budget<select name="budget" defaultValue="Let’s discuss"><option>Let’s discuss</option><option>Under £500</option><option>£500–£1,000</option><option>£1,000–£2,500</option><option>£2,500+</option></select></label><label>Ideal timeline<input name="timeline" maxLength={120} placeholder="A date, a month, or flexible"/></label></div><label>A little about your project<textarea name="message" required rows={5} maxLength={4000} placeholder="Tell me about your brand, audience, deliverables and the story you’d like to tell…"/></label><p className="form-note">This prepares your enquiry in your email app. Nothing is sent until you send the email.</p><button className="button" type="submit">Prepare my enquiry <ArrowUpRight size={18}/></button></form>{brief&&<div className="brief-ready" role="status"><span className="eyebrow"><Check size={16}/> YOUR ENQUIRY IS READY</span><h3>Let’s put the idea in my inbox.</h3><pre>{brief}</pre><div className="button-row"><a className="button" href={`mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(brief)}`}><Mail size={16}/> Open email to Beth</a><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(`To: ${email}\nSubject: ${subject}\n\n${brief}`);setCopied(true);}catch{setCopied(false);}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"Copied":"Copy enquiry"}</button></div><p className="form-note">No email app? Copy the enquiry and send it to <a href={`mailto:${email}`}>{email}</a>.</p></div>}</div>;
}
